---
title: "LAPS: Graphs and Tables"
output: pdf_document
toc: true
toc_depth: 2
number_sections: true
fontsize: 10pt
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
```


```{r preliminaries, echo=FALSE, message=FALSE, warning=FALSE}
# loadings:data
cat("\014")
rm(list=ls())
#setwd("/Users/hectorbahamonde/RU/research/Clientelism_paper/Paper_Presentation")

# Load the data
library(foreign) # install.packages("foreign") 
dat <- read.dta("/Users/hectorbahamonde/RU/research/Clientelism_paper/datasets/clientelism.dta")

# Recoding vars
dat <- na.omit(dat)
dat$ed <- as.numeric(dat$ed)
dat$vb3 <- as.numeric(dat$vb3)
dat$exc7 <- as.numeric(dat$exc7)
dat$polinv <- as.numeric(dat$polinv)
dat$polinv <- as.numeric(dat$polinv)
dat$polinv1 <- as.numeric(dat$polinv1)
dat$polinv2 <- as.numeric(dat$polinv2)
dat$polinv3 <- as.numeric(dat$polinv3)
dat$polinv4 <- as.numeric(dat$polinv4)
dat$polinv5 <- as.numeric(dat$polinv5)
dat$ing4 <- as.numeric(dat$ing4)


# constructing relative wealth index (Cordova 2009)
library(car) # install.packages("car") 
dat$wealth1 = recode(as.numeric(dat$wealth1), "1 = 0 ; 2 = 1")
dat$wealth2 = recode(as.numeric(dat$wealth2), "1 = 0 ; 2 = 1")
dat$wealth3 = recode(as.numeric(dat$wealth3), "1 = 0 ; 2 = 1")
dat$wealth4 = recode(as.numeric(dat$wealth4), "1 = 0 ; 2 = 1")
dat$wealth5 = recode(as.numeric(dat$wealth5), "1 = 0 ; 2 = 1 ; 3 = 2 ; 4 = 3")
dat$wealth6 = recode(as.numeric(dat$wealth6), "1 = 0 ; 2 = 1")
dat$wealth7 = recode(as.numeric(dat$wealth7), "1 = 0 ; 2 = 1")
dat$wealth8 = recode(as.numeric(dat$wealth8), "1 = 0 ; 2 = 1")
dat$wealth9 = recode(as.numeric(dat$wealth9), "1 = 0 ; 2 = 1")
dat$wealth10 = recode(as.numeric(dat$wealth10), "1 = 0 ; 2 = 1")

## splitting df in two
dat.ur <- subset(dat, dat$urban == "Ur")
dat.ru <- subset(dat, dat$urban == "Ru")



## PCA for RURAL and URBAN
wealth.dat.ur = data.frame(dat.ur$wealth1,dat.ur$wealth2,dat.ur$wealth3, dat.ur$wealth4, dat.ur$wealth5, dat.ur$wealth6, dat.ur$wealth7, dat.ur$wealth8, dat.ur$wealth9, dat.ur$wealth10)
wealth.dat.ru = data.frame(dat.ru$wealth1,dat.ru$wealth2,dat.ru$wealth3, dat.ru$wealth4, dat.ru$wealth5, dat.ru$wealth6, dat.ru$wealth7, dat.ru$wealth8, dat.ru$wealth9, dat.ru$wealth10)


dat.ur$wealth = 
  (princomp(wealth.dat.ur, scores = T)$scores[,1] * (dat.ur$wealth1-mean(dat.ur$wealth1) / sd(dat.ur$wealth1))) + 
  (princomp(wealth.dat.ur, scores = T)$scores[,2] * (dat.ur$wealth1-mean(dat.ur$wealth2) / sd(dat.ur$wealth2))) + 
  (princomp(wealth.dat.ur, scores = T)$scores[,3] * (dat.ur$wealth1-mean(dat.ur$wealth3) / sd(dat.ur$wealth3))) + 
  (princomp(wealth.dat.ur, scores = T)$scores[,4] * (dat.ur$wealth1-mean(dat.ur$wealth4) / sd(dat.ur$wealth4))) + 
  (princomp(wealth.dat.ur, scores = T)$scores[,5] * (dat.ur$wealth1-mean(dat.ur$wealth5) / sd(dat.ur$wealth5))) + 
  (princomp(wealth.dat.ur, scores = T)$scores[,6] * (dat.ur$wealth1-mean(dat.ur$wealth6) / sd(dat.ur$wealth6))) + 
  (princomp(wealth.dat.ur, scores = T)$scores[,7] * (dat.ur$wealth1-mean(dat.ur$wealth7) / sd(dat.ur$wealth7))) + 
  (princomp(wealth.dat.ur, scores = T)$scores[,8] * (dat.ur$wealth1-mean(dat.ur$wealth8) / sd(dat.ur$wealth8))) + 
  (princomp(wealth.dat.ur, scores = T)$scores[,9] * (dat.ur$wealth1-mean(dat.ur$wealth9) / sd(dat.ur$wealth9))) + 
  (princomp(wealth.dat.ur, scores = T)$scores[,10] * (dat.ur$wealth1-mean(dat.ur$wealth10) / sd(dat.ur$wealth10)))        



dat.ru$wealth = 
  (princomp(wealth.dat.ru, scores = T)$scores[,1] * (dat.ru$wealth1-mean(dat.ru$wealth1) / sd(dat.ru$wealth1))) + 
  (princomp(wealth.dat.ru, scores = T)$scores[,2] * (dat.ru$wealth1-mean(dat.ru$wealth2) / sd(dat.ru$wealth2))) + 
  (princomp(wealth.dat.ru, scores = T)$scores[,3] * (dat.ru$wealth1-mean(dat.ru$wealth3) / sd(dat.ru$wealth3))) + 
  (princomp(wealth.dat.ru, scores = T)$scores[,4] * (dat.ru$wealth1-mean(dat.ru$wealth4) / sd(dat.ru$wealth4))) + 
  (princomp(wealth.dat.ru, scores = T)$scores[,5] * (dat.ru$wealth1-mean(dat.ru$wealth5) / sd(dat.ru$wealth5))) + 
  (princomp(wealth.dat.ru, scores = T)$scores[,6] * (dat.ru$wealth1-mean(dat.ru$wealth6) / sd(dat.ru$wealth6))) + 
  (princomp(wealth.dat.ru, scores = T)$scores[,7] * (dat.ru$wealth1-mean(dat.ru$wealth7) / sd(dat.ru$wealth7))) + 
  (princomp(wealth.dat.ru, scores = T)$scores[,8] * (dat.ru$wealth1-mean(dat.ru$wealth8) / sd(dat.ru$wealth8))) + 
  (princomp(wealth.dat.ru, scores = T)$scores[,9] * (dat.ru$wealth1-mean(dat.ru$wealth9) / sd(dat.ru$wealth9))) + 
  (princomp(wealth.dat.ru, scores = T)$scores[,10] * (dat.ru$wealth1-mean(dat.ru$wealth10) / sd(dat.ru$wealth10)))  

## combining the two DF's
dat = rbind(dat.ur, dat.ru)


# municipal population from census
pop.municipalities = data.frame(
  municipality=c( "Acopiara", "Aloandia", "Aparecida de Goiania", "Belo Horizonte", "Belem", "Blumenau", "Branquinha",  "Brasilia", # 1
                  "Capela",  "Coronel Ezequiel", "Cuiaba", "Curitibanos", "Duque de Caxias", "Embu Guacu", "Fortaleza", "Franca",  # 2
                  "Itagiba", "Itaguaje", "Itumbiara", "Itupeva", "Jaboatao dos Guararapes", "Jaciara", "Jaragua do Sul", "Ji Parana", # 3
                  "Jijoca de Jericoacoara", "Juazeiro", "Lontra", "Marilia", "Minacu", "Mogi das Cruzes", "Mossoro", "Narandiba", # 4
                  "Pacaja", "Passos", "Pelotas", "Ponta Grossa", "Porecatu", "Porto Esperidiao", "Porto Velho", "Pocoes", "Progresso", # 5
                  "Redencao", "Rio Bonito", "Rio Branco", "Rio de Janeiro", "Senador Guiomard", "Sao Jose dos Campos", "Sao Joao del Rei", # 6
                  "Sao Lourenco", "Sao Paulo", "Timbauba", "Uaua", "Vera Cruz", "Vilhena"),  # 7
  pop=c(51160, 2051, 455657, 2375151, 4551, 309011, 10583, 2570160, # 1
        17077, 5405, 551098, 37748, 855048, 62769, 2452185, 318640, # 2
        15193, 4568, 92883, 44859, 644620, 25647, 143123, 116610, # 3
        17002, 197965, 8397, 216745, 31154, 387779, 259815, 4288, # 4
        39979, 106290, 328275, 311611, 14189, 11031, 428527, 44701, 6163, # 5
        26415, 55551, 336038, 6320446, 20179, 629921, 84469, # 6
        41657, 11253503, 53825, 24294, 23983, 76202) # 7 CORREGIR VERA CRUZ Y VER QUE ESTADO SON LAS OBS QUE TENGO, HAY COMO 4 VERA CRUCES
)

## merge datasets
dat = merge(dat, pop.municipalities, by=c("municipality"), all.x =T)


# create variable large
library(foreign)
wagehalf.d <- read.dta("/Users/hectorbahamonde/RU/research/Clientelism_paper/datasets/proportionofpoorcensus.dta")

wagehalf.d = data.frame(cbind(municipality = c( "Acopiara", "Aloandia", "Aparecida de Goiania", "Belo Horizonte", "Belem", "Blumenau", "Branquinha",  "Brasilia", # 1
                                                "Capela",  "Coronel Ezequiel", "Cuiaba", "Curitibanos", "Duque de Caxias", "Embu Guacu", "Fortaleza", "Franca",  # 2
                                                "Itagiba", "Itaguaje", "Itumbiara", "Itupeva", "Jaboatao dos Guararapes", "Jaciara", "Jaragua do Sul", "Ji Parana", # 3
                                                "Jijoca de Jericoacoara", "Juazeiro", "Lontra", "Marilia", "Minacu", "Mogi das Cruzes", "Mossoro", "Narandiba", # 4
                                                "Pacaja", "Passos", "Pelotas", "Ponta Grossa", "Porecatu", "Porto Esperidiao", "Porto Velho", "Pocoes", "Progresso", # 5
                                                "Redencao", "Rio Bonito", "Rio Branco", "Rio de Janeiro", "Senador Guiomard", "Sao Jose dos Campos", "Sao Joao del Rei", # 6
                                                "Sao Lourenco", "Sao Paulo", "Timbauba", "Uaua", "Vera Cruz", "Vilhena"), 
                              large = as.numeric(wagehalf.d$wagehalf >= median(wagehalf.d$wagehalf))
)
)
dat = merge(dat, wagehalf.d, by=c("municipality"), all.x =T)

## recode large
library(car) # install.packages("car") 
dat$large <- as.numeric(dat$large)
dat$large <- recode(dat$large, "1 = 0 ; 2 = 1")


## transform the wagehalf variable
dat$wagehalf = round(dat$wagehalf, digits=0)


# Transform the continuous "treatment" variable in four segments
wagehalf.4 = cut(dat$wagehalf, breaks = c(0,
                                          quantile(dat$wagehalf, .25), 
                                          quantile(dat$wagehalf, .50), 
                                          quantile(dat$wagehalf, .75), 
                                          quantile(dat$wagehalf, 1)), include.lowest=T, labels=c("0-25","25-50","50-75","75-100")
)

dat$wagehalf.4 = as.numeric(wagehalf.4)

# Transform the continuous "pop" variable in ten segments // mostly for simulation purposes
pop.10.m = cut(dat$pop, breaks = c(0,
                                   quantile(dat$pop, .10), 
                                   quantile(dat$pop, .20), 
                                   quantile(dat$pop, .30), 
                                   quantile(dat$pop, .40),
                                   quantile(dat$pop, .50),
                                   quantile(dat$pop, .60),
                                   quantile(dat$pop, .70),
                                   quantile(dat$pop, .80),
                                   quantile(dat$pop, .90),
                                   quantile(dat$pop, 1)
), 
include.lowest=T, labels=c(
  "0-10","11-20","21-30","31-40", "41-50", "51-60", "61-70", "71-80", "81-90", "91-100")
)


pop.10.r = cut(dat$pop, breaks = c(0,
                                   quantile(dat$pop, .10), 
                                   quantile(dat$pop, .20), 
                                   quantile(dat$pop, .30), 
                                   quantile(dat$pop, .40),
                                   quantile(dat$pop, .50),
                                   quantile(dat$pop, .60),
                                   quantile(dat$pop, .70),
                                   quantile(dat$pop, .80),
                                   quantile(dat$pop, .90),
                                   quantile(dat$pop, 1)), 
               include.lowest=T, labels=c(
                 "0-10",
                 "11-20",
                 "21-30",
                 "31-40",
                 "41-50",
                 "51-60",
                 "61-70", 
                 "71-80", 
                 "81-90",
                 "91-100")
)

## attaching
dat$pop.10 = as.numeric(pop.10.r)


# save unmatched dataset
save(dat, file = "/Users/hectorbahamonde/RU/research/Clientelism_paper/datasets/dat.RData")


# Constructing Matched Set
set.seed(604)
library(MatchIt) # install.packages("MatchIt", dependencies=TRUE)
# m.out <- matchit(large ~ wealth + urban + munopp + polinv,
m.out <- matchit(large ~ wealth + munopp + polinv,
                 discard = "hull.both", 
                 method = "cem",
                 data = dat,
                 verbose = F
)


#print. <- print(m.out)
sum.match = summary(m.out)


# Match Data
m.data <- match.data(m.out)


# Recode client1dummy after matching
library(car) # install.packages("car") 
m.data$clien1dummy <- as.numeric(m.data$clien1dummy)
m.data$clien1dummy <- recode(m.data$clien1dummy, "1 = 0 ; 2 = 1")

# save matched dataset
save(m.data, file = "/Users/hectorbahamonde/RU/research/Clientelism_paper/datasets/mdata.RData")


# Generating the Propensity Score 
library(CBPS, quietly = T) # install.packages("CBPS")
fit <- CBPS(as.factor(wagehalf.4) ~  wealth + munopp + polinv,
            #wealth,# + polinv,# + munopp + polinv + ing4,  # wealth + munopp + polinv
            data = dat, 
            iterations = 25000, 
            twostep = TRUE, # F
            method = "over", # EXACT
            ATT = 0, # 2
            standardize = F) # F


## transform the weight var. // Attaching weights to DF // sorting for GEE models
dat$weights = as.numeric(fit$weights)

save(dat, file = "/Users/hectorbahamonde/RU/research/Clientelism_paper/datasets/dat.RData")
```




```{r , echo=FALSE, message=FALSE, warning=FALSE}
#  municipality:income:large:plot:matched
## HIGH df
high.d = data.frame(
  Municipality = as.factor(m.data$municipality[m.data$large == 1]),
  Density = c(rep("High", length(m.data$municipality[as.numeric(m.data$large == 1)]))),
  Wealth = as.numeric(m.data$wealth)[m.data$large == 1]
)

## LOW df
low.d = data.frame(
  Municipality = as.factor(m.data$municipality[m.data$large == 0]),
  Density = c(rep("Low", length(m.data$municipality[as.numeric(m.data$large == 0)]))),
  Wealth = as.numeric(m.data$wealth)[m.data$large == 0]
)

## rbinding the two of them
density.d = data.frame(rbind(high.d, low.d))
#density.d$Wealth = as.numeric((density.d$Wealth-min(density.d$Wealth))/(max(density.d$Wealth)-min(density.d$Wealth))*60)

## plot
library(ggplot2)
ggplot(density.d, aes(factor(Municipality), fill = Density)) + 
  geom_bar() + 
  geom_point(data=density.d, 
             position = position_jitter(width = 0.6), 
             size = I(1),
             aes(
               x=as.factor(Municipality), 
               y=Wealth,
               alpha=Wealth))+
  #coord_flip() +
  xlab("") + 
  ylab("Frequency (matched set)") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        legend.key = element_rect(colour = NA, fill = NA, size = 0.5))
```



```{r , echo=FALSE, message=FALSE, warning=FALSE}
# tgraph:plot
## Plot Density
library(ggplot2)
ggplot() + 
  geom_density(aes(x=m.data$wagehalf), fill = "forestgreen", alpha = .2) + 
  geom_segment(data= 
                 m.data, aes(
                   x = (wagehalf=median(m.data$wagehalf)), 
                   y = 0, 
                   xend = (wagehalf=median(m.data$wagehalf)), 
                   yend = .0305), 
               linetype="dashed", 
               size=1.5, 
               colour = "forestgreen") + 
               xlab("Percentage of People Living with \n Less than Half of the Minimum Wage") + 
               ylab("Density") + 
               theme_bw()
```





```{r , echo=FALSE, message=FALSE, warning=FALSE}
# balance:plot
##
library(ggplot2)
library(gtable)
library(gridExtra)
library(cowplot)

# matched

balance.1.m=ggplot() + 
  geom_density(aes(x=as.numeric(m.data$wealth), colour =factor(m.data$large,levels = c(0,1),labels = c("Low", "High")))) + 
  ylab("Matched Set") + 
  xlab("Wealth Index") + 
  theme_bw() +
  scale_x_continuous(limits = c(min(dat$wealth), max(dat$wealth))) +
  theme(axis.title=element_text(size=10), legend.text = element_text(size = 10), legend.title = element_text(size = 10))  + scale_colour_discrete(name = "Density of the Poor")

balance.3.m=ggplot() + 
  geom_density(aes(x=as.numeric(m.data$munopp), colour = factor(m.data$large,levels = c(0,1),labels = c("Low", "High")))) + 
  ylab("") + 
  xlab("Municipal Opposition") + 
  theme_bw() +
  scale_x_continuous(limits = c(min(dat$munopp), max(dat$munopp))) +
  theme(axis.title=element_text(size=10), legend.text = element_text(size = 10), legend.title = element_text(size = 10))  + scale_colour_discrete(name = "Density of the Poor")

balance.4.m=ggplot() + 
  geom_density(aes(x=as.numeric(m.data$polinv), colour =factor(m.data$large,levels = c(0,1),labels = c("Low", "High")))) + 
  ylab("") + 
  xlab("Political Involvement") + 
  theme_bw() + 
  scale_x_continuous(limits = c(min(dat$polinv), max(dat$polinv))) +
  theme(axis.title=element_text(size=10), legend.text = element_text(size = 10), legend.title = element_text(size = 10))  + scale_colour_discrete(name = "Density of the Poor")

# RAW

balance.1.r=ggplot() + 
  geom_density(aes(x=as.numeric(dat$wealth), colour =factor(dat$large,levels = c(0,1),labels = c("Low", "High")))) + 
  ylab("Raw Set") + 
  xlab("Wealth Index") + 
  theme_bw() +
  ylim(limits = c(0, 0.085)) +
  theme(axis.title=element_text(size=10), legend.text = element_text(size = 10), legend.title = element_text(size = 10))  + scale_colour_discrete(name = "Density of the Poor")

balance.3.r=ggplot() + 
  geom_density(aes(x=as.numeric(dat$munopp), colour =factor(dat$large,levels = c(0,1),labels = c("Low", "High")))) + 
  ylab("") + 
  xlab("Municipal Opposition") + 
  theme_bw() +
  scale_x_continuous(limits = c(min(dat$munopp), max(dat$munopp))) +
  theme(axis.title=element_text(size=10), legend.text = element_text(size = 10), legend.title = element_text(size = 10))  + scale_colour_discrete(name = "Density of the Poor")

balance.4.r=ggplot() + 
  geom_density(aes(x=as.numeric(dat$polinv), colour =factor(dat$large,levels = c(0,1),labels = c("Low", "High")))) + 
  ylab("") + 
  xlab("Political Involvement") + 
  theme_bw() +
  scale_x_continuous(limits = c(min(dat$polinv), max(dat$polinv))) +
  theme(axis.title=element_text(size=10), legend.text = element_text(size = 10), legend.title = element_text(size = 10))  + scale_colour_discrete(name = "Density of the Poor")


plots <- plot_grid(
  balance.1.m + theme(legend.position="none"), 
  balance.3.m + theme(legend.position="none"), 
  balance.4.m + theme(legend.position="none"), 
  balance.1.r + theme(legend.position="none"), 
  balance.3.r + theme(legend.position="none"), 
  balance.4.r + theme(legend.position="none"),
  align = 'vh', 
  hjust = -1, 
  nrow = 2,
  ncol = 3
)

grobs <- ggplotGrob(balance.4.r + theme(legend.position="bottom"))$grobs
legend <- grobs[[which(sapply(grobs, function(x) x$name) == "guide-box")]]
plot_grid(plots, legend, ncol = 1, rel_heights = c(1, .2))
```




```{r , echo=FALSE, message=FALSE, warning=FALSE}
# plot:four:quadrants
##########################
##### Estimate the models
##########################
# load data
load("/Users/hectorbahamonde/RU/research/Clientelism_paper/datasets/mdata.RData")
load("/Users/hectorbahamonde/RU/research/Clientelism_paper/datasets/dat.RData")

## Recode Before modeling
dat$clien1dummy <- as.numeric(dat$clien1dummy)
library(car)
dat$clien1dummy <- recode(dat$clien1dummy, "1 = 0 ; 2 = 1")

# formulas
model.m = formula(clien1dummy ~ wealth*munopp*large + pop.10 + polinv + ing4 + vb3 + exc7 + ed)
model.gps = formula(clien1dummy ~ wealth*munopp*wagehalf.4 + pop.10 + polinv + ing4 + vb3 + exc7 + ed + weights)



library(Zelig)
model.m.s = zelig(model.m, 
                       model = "logit.gee",
                       id = "municipality", 
                       weights = "wt",
                       std.err = "san.se",
                       corstr = "exchangeable",
                       data = m.data, 
                  cite = F)

##########################
##### BY Competition and Income
##########################
set.seed(602); options(scipen=999)

# simulation DISTRIBUTION PLOTS
library(Zelig)
high.poor.lowcomp = data.frame(competition = rep("Low Competition", 1000000), income = rep("Poor Individuals", 1000000), x = sim(x = setx(model.m.s, cond = TRUE,large = max(m.data$large), wealth= quantile(m.data$wealth, .25), munopp = min(m.data$munopp)), num=1000000)$getqi(qi="ev"))
high.poor.highcomp = data.frame(competition = rep("High Competition", 1000000),income = rep("Poor Individuals", 1000000), x = sim(x = setx(model.m.s, cond = TRUE,large = max(m.data$large), wealth= quantile(m.data$wealth, .25), munopp = max(m.data$munopp)), num=1000000)$getqi(qi="ev"))
high.rich.lowcomp = data.frame(competition = rep("Low Competition", 1000000),income = rep("Non-Poor Individuals", 1000000), x= sim(x = setx(model.m.s, cond = TRUE,large = max(m.data$large), wealth= quantile(m.data$wealth, .75), munopp = min(m.data$munopp)), num=1000000)$getqi(qi="ev"))
high.rich.highcomp = data.frame(competition = rep("High Competition", 1000000),income = rep("Non-Poor Individuals", 1000000), x= sim(x = setx(model.m.s, cond = TRUE,large = max(m.data$large), wealth= quantile(m.data$wealth, .75), munopp = max(m.data$munopp)), num=1000000)$getqi(qi="ev"))
low.poor.lowcomp = data.frame(competition = rep("Low Competition", 1000000),income = rep("Poor Individuals", 1000000), x= sim(x = setx(model.m.s, cond = TRUE,large = min(m.data$large), wealth= quantile(m.data$wealth, .25), munopp = min(m.data$munopp)), num=1000000)$getqi(qi="ev"))
low.poor.highcomp = data.frame(competition = rep("High Competition", 1000000),income = rep("Poor Individuals", 1000000), x= sim(x = setx(model.m.s, cond = TRUE,large = min(m.data$large), wealth= quantile(m.data$wealth, .25), munopp = max(m.data$munopp)), num=1000000)$getqi(qi="ev"))
low.rich.lowcomp = data.frame(competition = rep("Low Competition", 1000000),income = rep("Non-Poor Individuals", 1000000), x= sim(x = setx(model.m.s, cond = TRUE,large = min(m.data$large), wealth= quantile(m.data$wealth, .75), munopp = min(m.data$munopp)), num=1000000)$getqi(qi="ev"))
low.rich.highcomp = data.frame(competition = rep("High Competition", 1000000),income = rep("Non-Poor Individuals", 1000000), x= sim(x = setx(model.m.s, cond = TRUE,large = min(m.data$large), wealth= quantile(m.data$wealth, .75), munopp = max(m.data$munopp)), num=1000000)$getqi(qi="ev"))

# plot
library(ggplot2)
ggplot() + 
  geom_density(aes(x=x, colour="High"), data= high.poor.lowcomp) + 
  geom_density(aes(x=x, colour="High"), data= high.poor.highcomp) + 
  geom_density(aes(x=x, colour="High"), data= high.rich.lowcomp) + 
  geom_density(aes(x=x, colour="High"), data= high.rich.highcomp) + 
  geom_density(aes(x=x, colour="Low"), data= low.poor.lowcomp) + 
  geom_density(aes(x=x, colour="Low"), data= low.poor.highcomp) + 
  geom_density(aes(x=x, colour="Low"), data= low.rich.lowcomp) + 
  geom_density(aes(x=x, colour="Low"), data= low.rich.highcomp) + 
  ylab("Estimated Density") + xlab("Expected Value of Clientelism") +
  theme_bw() +
  theme(axis.title=element_text(size=10), legend.text = element_text(size = 10), legend.title = element_text(size = 10))  + scale_colour_discrete(name = "Density of the Poor") +
  facet_grid(competition~income, scales ="free")
```



```{r , echo=FALSE, message=FALSE, warning=FALSE}
# pol.inv:pop.size:plot
##########################
#  LARGE * POLINV: 
##########################

library(Zelig)
set.seed(602); options(scipen=999)


# low 
model.m.s.low = data.frame(
  sim(
    x = setx(model.m.s, cond = TRUE,
             large = min(m.data$large), 
             polinv:large,
             polinv = min(m.data$polinv):max(m.data$polinv)), 
    num=700)$getqi(qi="ev", xvalue="range"))

colnames(model.m.s.low) <- seq(1:ncol(as.data.frame(t(min(m.data$polinv):max(m.data$polinv)))))  # low

# high
model.m.s.high = data.frame(
  sim(
    x = setx(model.m.s, cond = TRUE,
             large = max(m.data$large), 
             polinv:large,
             polinv = min(m.data$polinv):max(m.data$polinv)), 
    num=700)$getqi(qi="ev", xvalue="range")) ; 
colnames(model.m.s.high) <- seq(1:ncol(as.data.frame(t(min(m.data$polinv):max(m.data$polinv)))))  # high


# polinv 
model.m.s.polinv = data.frame(
  sim(x = setx(model.m.s, cond = TRUE,
               large:munopp,
               polinv = min(m.data$polinv):max(m.data$polinv)), 
      num=300)$getqi(qi="ev", xvalue="range"))
colnames(model.m.s.polinv) <- seq(1:ncol(as.data.frame(t(min(m.data$polinv):max(m.data$polinv)))))  


# to compute confidence intervals
library(Rmisc) # install.packages("Rmisc")

### df's
### low
df.low = data.frame(
  mean = c(mean(model.m.s.low$`1`),mean(model.m.s.low$`2`),mean(model.m.s.low$`3`),mean(model.m.s.low$`4`),mean(model.m.s.low$`5`),mean(model.m.s.low$`6`),mean(model.m.s.low$`7`),mean(model.m.s.low$`8`)),
  Type = rep("Low Density", ncol(model.m.s.low)),
  Opposition = min(m.data$polinv):max(m.data$polinv),
  Upper = c(as.numeric(CI(model.m.s.low$`1`)[1]), as.numeric(CI(model.m.s.low$`2`)[1]), as.numeric(CI(model.m.s.low$`3`)[1]), as.numeric(CI(model.m.s.low$`4`)[1]), as.numeric(CI(model.m.s.low$`5`)[1]), as.numeric(CI(model.m.s.low$`6`)[1]), as.numeric(CI(model.m.s.low$`7`)[1]), as.numeric(CI(model.m.s.low$`8`)[1])),
  Lower = c(
    as.numeric(CI(model.m.s.low$`1`)[3]), as.numeric(CI(model.m.s.low$`2`)[3]), as.numeric(CI(model.m.s.low$`3`)[3]), as.numeric(CI(model.m.s.low$`4`)[3]), as.numeric(CI(model.m.s.low$`5`)[3]), as.numeric(CI(model.m.s.low$`6`)[3]), as.numeric(CI(model.m.s.low$`7`)[3]), as.numeric(CI(model.m.s.low$`8`)[3]))
)

### high
df.high = data.frame(
  mean = c(mean(model.m.s.high$`1`),mean(model.m.s.high$`2`),mean(model.m.s.high$`3`),mean(model.m.s.high$`4`),mean(model.m.s.high$`5`),mean(model.m.s.high$`6`),mean(model.m.s.high$`7`),mean(model.m.s.high$`8`)),
  Type = rep("High Density", ncol(model.m.s.high)),
  Opposition = min(m.data$polinv):max(m.data$polinv),
  Upper = c(as.numeric(CI(model.m.s.high$`1`)[1]), as.numeric(CI(model.m.s.high$`2`)[1]), as.numeric(CI(model.m.s.high$`3`)[1]), as.numeric(CI(model.m.s.high$`4`)[1]), as.numeric(CI(model.m.s.high$`5`)[1]), as.numeric(CI(model.m.s.high$`6`)[1]), as.numeric(CI(model.m.s.high$`7`)[1]), as.numeric(CI(model.m.s.high$`8`)[1])),
  Lower = c(
    as.numeric(CI(model.m.s.high$`1`)[3]), as.numeric(CI(model.m.s.high$`2`)[3]), as.numeric(CI(model.m.s.high$`3`)[3]), as.numeric(CI(model.m.s.high$`4`)[3]), as.numeric(CI(model.m.s.high$`5`)[3]), as.numeric(CI(model.m.s.high$`6`)[3]), as.numeric(CI(model.m.s.high$`7`)[3]), as.numeric(CI(model.m.s.high$`8`)[3]))
)

### polinv
df.polinv.alone = data.frame(
  mean = c(mean(model.m.s.polinv$`1`),mean(model.m.s.polinv$`2`),mean(model.m.s.polinv$`3`),mean(model.m.s.polinv$`4`),mean(model.m.s.polinv$`5`),mean(model.m.s.polinv$`6`),mean(model.m.s.polinv$`7`),mean(model.m.s.polinv$`8`)),
  Type = rep("Political Involvement", ncol(model.m.s.polinv)),
  Opposition = min(m.data$polinv):max(m.data$polinv),
  Upper = c(as.numeric(CI(model.m.s.polinv$`1`)[1]), as.numeric(CI(model.m.s.polinv$`2`)[1]), as.numeric(CI(model.m.s.polinv$`3`)[1]), as.numeric(CI(model.m.s.polinv$`4`)[1]), as.numeric(CI(model.m.s.polinv$`5`)[1]), as.numeric(CI(model.m.s.polinv$`6`)[1]), as.numeric(CI(model.m.s.polinv$`7`)[1]), as.numeric(CI(model.m.s.polinv$`8`)[1])),
  Lower =c(as.numeric(CI(model.m.s.polinv$`1`)[3]), as.numeric(CI(model.m.s.polinv$`2`)[3]), as.numeric(CI(model.m.s.polinv$`3`)[3]), as.numeric(CI(model.m.s.polinv$`4`)[3]), as.numeric(CI(model.m.s.polinv$`5`)[3]), as.numeric(CI(model.m.s.polinv$`6`)[3]), as.numeric(CI(model.m.s.polinv$`7`)[3]), as.numeric(CI(model.m.s.polinv$`8`)[3]))
)

### combined two df's
polinv.d= rbind(df.high, df.low,df.polinv.alone)


### plot
library(ggplot2)
p1= ggplot(polinv.d, aes(x=Opposition, y=mean, colour=Type)) + 
  stat_smooth() + 
  geom_ribbon(aes(ymin=Lower, ymax=Upper, linetype=NA), alpha=0.2) +
  stat_smooth(aes(x=Opposition,y=mean)) +
  xlab("Political Involvement") + ylab("Expected Value of Clientelism") + 
  theme_bw() + 
  theme(legend.position="top", legend.title=element_blank(), legend.key = element_rect())

##########################
#  LARGE * POP
##########################

## low 
model.m.s.low = data.frame(
  sim(x = setx(model.m.s, cond = TRUE,
               large = min(m.data$large), 
               pop.10 = min(m.data$pop.10):max(m.data$pop.10)), 
      num=300)$getqi(qi="ev", xvalue="range"))
colnames(model.m.s.low) <- seq(1:ncol(as.data.frame(t(min(m.data$pop.10):max(m.data$pop.10)))))  # low


## high
gee.dich.m.2.high = data.frame(
  sim(x = setx(model.m.s, cond = TRUE,
               large = max(m.data$large), 
               pop.10 = min(m.data$pop.10):max(m.data$pop.10)),num=300)$getqi(qi="ev", xvalue="range"))
colnames(gee.dich.m.2.high) <- seq(1:ncol(as.data.frame(t(min(m.data$pop.10):max(m.data$pop.10)))))  # high


## pop.10
gee.dich.m.2.pop.10 = data.frame(
  sim(x = setx(model.m.s, cond = TRUE,
               pop.10 = min(m.data$pop.10):max(m.data$pop.10)),num=300)$getqi(qi="ev", xvalue="range"))
colnames(gee.dich.m.2.pop.10) <- seq(1:ncol(as.data.frame(t(min(m.data$pop.10):max(m.data$pop.10)))))  # high



library(Rmisc) # install.packages("Rmisc")

### low
df.low = data.frame(
  mean = c(mean(model.m.s.low$`1`),mean(model.m.s.low$`2`),mean(model.m.s.low$`3`),mean(model.m.s.low$`4`),mean(model.m.s.low$`5`),mean(model.m.s.low$`6`),mean(model.m.s.low$`7`),mean(model.m.s.low$`8`), mean(model.m.s.low$`9`),mean(model.m.s.low$`10`)),
  Population = min(m.data$pop.10):max(m.data$pop.10),
  Poverty = rep("Low Density", ncol(model.m.s.low)),
  Upper = c(as.numeric(CI(model.m.s.low$`1`)[1]), as.numeric(CI(model.m.s.low$`2`)[1]), as.numeric(CI(model.m.s.low$`3`)[1]), as.numeric(CI(model.m.s.low$`4`)[1]), as.numeric(CI(model.m.s.low$`5`)[1]), as.numeric(CI(model.m.s.low$`6`)[1]), as.numeric(CI(model.m.s.low$`7`)[1]), as.numeric(CI(model.m.s.low$`8`)[1]), as.numeric(CI(model.m.s.low$`9`)[1]), as.numeric(CI(model.m.s.low$`10`)[1])),
  Lower =c(as.numeric(CI(model.m.s.low$`1`)[3]), as.numeric(CI(model.m.s.low$`2`)[3]), as.numeric(CI(model.m.s.low$`3`)[3]), as.numeric(CI(model.m.s.low$`4`)[3]), as.numeric(CI(model.m.s.low$`5`)[3]), as.numeric(CI(model.m.s.low$`6`)[3]), as.numeric(CI(model.m.s.low$`7`)[3]), as.numeric(CI(model.m.s.low$`8`)[3]), as.numeric(CI(model.m.s.low$`9`)[3]), as.numeric(CI(model.m.s.low$`10`)[3]))
)

### high
df.high = data.frame(
  mean = c(mean(gee.dich.m.2.high$`1`),mean(gee.dich.m.2.high$`2`),mean(gee.dich.m.2.high$`3`),mean(gee.dich.m.2.high$`4`),mean(gee.dich.m.2.high$`5`),mean(gee.dich.m.2.high$`6`),mean(gee.dich.m.2.high$`7`),mean(gee.dich.m.2.high$`8`), mean(gee.dich.m.2.high$`9`),mean(gee.dich.m.2.high$`10`)),
  Population = min(m.data$pop.10):max(m.data$pop.10),
  Poverty = rep("High Density", ncol(gee.dich.m.2.high)),
  Upper = c(as.numeric(CI(gee.dich.m.2.high$`1`)[1]), as.numeric(CI(gee.dich.m.2.high$`2`)[1]), as.numeric(CI(gee.dich.m.2.high$`3`)[1]), as.numeric(CI(gee.dich.m.2.high$`4`)[1]), as.numeric(CI(gee.dich.m.2.high$`5`)[1]), as.numeric(CI(gee.dich.m.2.high$`6`)[1]), as.numeric(CI(gee.dich.m.2.high$`7`)[1]), as.numeric(CI(gee.dich.m.2.high$`8`)[1]), as.numeric(CI(gee.dich.m.2.high$`9`)[1]), as.numeric(CI(gee.dich.m.2.high$`10`)[1])),
  Lower =c(as.numeric(CI(gee.dich.m.2.high$`1`)[3]), as.numeric(CI(gee.dich.m.2.high$`2`)[3]), as.numeric(CI(gee.dich.m.2.high$`3`)[3]), as.numeric(CI(gee.dich.m.2.high$`4`)[3]), as.numeric(CI(gee.dich.m.2.high$`5`)[3]), as.numeric(CI(gee.dich.m.2.high$`6`)[3]), as.numeric(CI(gee.dich.m.2.high$`7`)[3]), as.numeric(CI(gee.dich.m.2.high$`8`)[3]), as.numeric(CI(gee.dich.m.2.high$`9`)[3]), as.numeric(CI(gee.dich.m.2.high$`10`)[3]))
)

### pop
df.pop.alone = data.frame(
  mean = c(mean(gee.dich.m.2.pop.10$`1`),mean(gee.dich.m.2.pop.10$`2`),mean(gee.dich.m.2.pop.10$`3`),mean(gee.dich.m.2.pop.10$`4`),mean(gee.dich.m.2.pop.10$`5`),mean(gee.dich.m.2.pop.10$`6`),mean(gee.dich.m.2.pop.10$`7`),mean(gee.dich.m.2.pop.10$`8`), mean(gee.dich.m.2.pop.10$`9`),mean(gee.dich.m.2.pop.10$`10`)),
  Population = min(m.data$pop.10):max(m.data$pop.10),
  Poverty = rep("Population Size", ncol(gee.dich.m.2.pop.10)),
  Upper = c(as.numeric(CI(gee.dich.m.2.pop.10$`1`)[1]), as.numeric(CI(gee.dich.m.2.pop.10$`2`)[1]), as.numeric(CI(gee.dich.m.2.pop.10$`3`)[1]), as.numeric(CI(gee.dich.m.2.pop.10$`4`)[1]), as.numeric(CI(gee.dich.m.2.pop.10$`5`)[1]), as.numeric(CI(gee.dich.m.2.pop.10$`6`)[1]), as.numeric(CI(gee.dich.m.2.pop.10$`7`)[1]), as.numeric(CI(gee.dich.m.2.pop.10$`8`)[1]), as.numeric(CI(gee.dich.m.2.pop.10$`9`)[1]), as.numeric(CI(gee.dich.m.2.pop.10$`10`)[1])),
  Lower =c(as.numeric(CI(gee.dich.m.2.pop.10$`1`)[3]), as.numeric(CI(gee.dich.m.2.pop.10$`2`)[3]), as.numeric(CI(gee.dich.m.2.pop.10$`3`)[3]), as.numeric(CI(gee.dich.m.2.pop.10$`4`)[3]), as.numeric(CI(gee.dich.m.2.pop.10$`5`)[3]), as.numeric(CI(gee.dich.m.2.pop.10$`6`)[3]), as.numeric(CI(gee.dich.m.2.pop.10$`7`)[3]), as.numeric(CI(gee.dich.m.2.pop.10$`8`)[3]), as.numeric(CI(gee.dich.m.2.pop.10$`9`)[3]), as.numeric(CI(gee.dich.m.2.pop.10$`10`)[3]))
)


### combined two df's
pop.d= rbind(df.high, df.low,df.pop.alone)



### plot
library(ggplot2)
p2= ggplot(pop.d, aes(x=Population, y=mean, colour=Poverty)) + 
  stat_smooth() + 
  geom_ribbon(aes(ymin=Lower, ymax=Upper, linetype=NA), alpha=0.2) +
  stat_smooth(aes(x=Population,y=mean)) +
  xlab("Municipal Population Size") + ylab("Expected Value of Clientelism") + 
  theme_bw() + 
  theme(axis.title.y=element_text(colour="white"), legend.position="top", legend.title=element_blank(), legend.key = element_rect())


###################################

library(cowplot) # install.packages("cowplot")
plot_grid(p1,p2,  nrow = 1, labels = "auto")
```




```{r , echo=FALSE, message=FALSE, warning=FALSE}
# tab:sum:stats:r

# whole sample
dat.clien1dummy <- dat$clien1dummy 
dat.clien1dummy <- as.numeric(dat.clien1dummy)
dat.clien1dummy <- recode(dat.clien1dummy, "1 = 0 ; 2 = 1")



dat.large <- dat$large 
dat.wealth <- dat$wealth 
dat.munopp <- dat$munopp
dat.polinv <- dat$polinv 

dat.exc7 <- dat$exc7 
dat.ing4 <- dat$ing4
dat.vb3 <- dat$vb3 

dat.urban <- dat$urban
dat.urban <- as.numeric(dat.urban)
dat.urban <- recode(dat.urban, "1 = 0 ; 2 = 1")

dat.ed <- dat$ed
dat.ed <- as.numeric(dat.ed)
dat.ed <- recode(dat.ed, "
                 1 = 0 ; 
                 2 = 1 ; 
                 3 = 2 ; 
                 4 = 3 ;
                 5 = 4 ;
                 6 = 5 ;
                 7 = 6 ;
                 8 = 7 ;
                 9 = 8 ;
                 10 = 9 ;
                 11 = 10 ;
                 12 = 11 ;
                 13 = 12 ;
                 14 = 13 ;
                 15 = 14 ;
                 16 = 15 ;
                 17 = 16")

dat.r <- data.frame(dat.clien1dummy, dat.large, dat.wealth, dat.munopp, dat.polinv, dat.exc7, dat.ing4, dat.vb3, dat.urban, dat.ed)


library(stargazer, quietly = T)
stargazer(dat.r, 
          summary=T, 
          title = "Summary Statistics: Raw Sample",
          label = "sumtab:raw",
          type = "latex",
          font.size = "scriptsize",
          style= "apsr",
          covariate.labels=c("Clientelism", "High Density", "Wealth Index", "Municipal Opposition", "Political Involvement", "Perception of Corruption", "Support for Democracy", "Party Id.", "Urban", "Years of Education"),
          table.placement = "h",
          notes.align = "c"
)
```



```{r , echo=FALSE, message=FALSE, warning=FALSE}
# tab:sum:stats:m
# matched sample
m.data.clien1dummy <- m.data$clien1dummy 
m.data.clien1dummy <- as.numeric(m.data.clien1dummy)
m.data.clien1dummy <- recode(m.data.clien1dummy, "1 = 0 ; 2 = 1")



m.data.large <- m.data$large 
m.data.wealth <- m.data$wealth 
m.data.munopp <- m.data$munopp
m.data.polinv <- m.data$polinv 

m.data.exc7 <- m.data$exc7 
m.data.ing4 <- m.data$ing4
m.data.vb3 <- m.data$vb3 

m.data.urban <- m.data$urban
m.data.urban <- as.numeric(m.data.urban)
m.data.urban <- recode(m.data.urban, "1 = 0 ; 2 = 1")

m.data.ed <- m.data$ed
m.data.ed <- as.numeric(m.data.ed)
m.data.ed <- recode(m.data.ed, "
                    1 = 0 ; 
                    2 = 1 ; 
                    3 = 2 ; 
                    4 = 3 ;
                    5 = 4 ;
                    6 = 5 ;
                    7 = 6 ;
                    8 = 7 ;
                    9 = 8 ;
                    10 = 9 ;
                    11 = 10 ;
                    12 = 11 ;
                    13 = 12 ;
                    14 = 13 ;
                    15 = 14 ;
                    16 = 15 ;
                    17 = 16")

dat.m <- data.frame(m.data.clien1dummy, m.data.large, m.data.wealth, m.data.munopp, m.data.polinv, m.data.exc7, m.data.ing4, m.data.vb3, m.data.urban, m.data.ed)


library(stargazer, quietly = T)
stargazer(dat.m, 
          summary=T, 
          title = "Summary Statistics: Matched Sample",
          label = "sumtab:matched",
          type = "latex",
          font.size = "scriptsize",
          style= "apsr",
          covariate.labels=c("Clientelism", "High Density", "Wealth Index", "Municipal Opposition", "Political Involvement", "Perception of Corruption", "Support for Democracy", "Party Id.", "Urban", "Years of Education"),
          table.placement = "h",
          notes.align = "c"
)
```



```{r , echo=FALSE, message=FALSE, warning=FALSE}
# municipality:sample:plot
load("/Users/hectorbahamonde/RU/research/Clientelism_paper/datasets/mdata.RData")
load("/Users/hectorbahamonde/RU/research/Clientelism_paper/datasets/dat.RData")


## df of matched set
municipality.m = data.frame(
  Municipality = as.factor(m.data$municipality),
  Sample = c(rep("Matched", length(m.data$municipality))
             )
)

## df of raw set
municipality.r = data.frame(
  Municipality = as.factor(dat$municipality),
  Sample = c(rep("Raw", length(dat$municipality))
  )
)

## rbinding the two of them
municipality.d = data.frame(rbind(municipality.m, municipality.r))
municipality.d = data.frame(table(municipality.d))

## plot
#library(ggplot2)
#ggplot(municipality.d, aes(factor(Municipality), Freq, fill = Sample)) + geom_bar(stat = "identity") + coord_flip() +
#  xlab("Municipality") + 
#  ylab("Frequency") + 
#  #coord_flip() +
#  theme_bw()

library(ggplot2)
#mun.p1 = 
  ggplot(municipality.d, aes(x = Municipality, y = Freq, fill = Sample)) + geom_bar(stat = "identity") +
  xlab("") + 
  ylab("Frequency") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        legend.key = element_rect(colour = NA, fill = NA, size = 0.5))

```


```{r , echo=FALSE, message=FALSE, warning=FALSE}
# tab:results
PENDING
```


```{r , echo=FALSE, message=FALSE, warning=FALSE}
# municipality:wealth:large:plot
load("/Users/hectorbahamonde/RU/research/Clientelism_paper/datasets/mdata.RData")
load("/Users/hectorbahamonde/RU/research/Clientelism_paper/datasets/dat.RData")

library(ggplot2)

### Matched Set
density.wealth.m= ggplot() + geom_point(
  aes(
    y=as.factor(m.data$large), 
    x=m.data$wealth, 
    colour=m.data$large,
    alpha = 1/length(m.data$wealth)), 
  position = position_jitter(width = 5)) +
  xlab("Wealth Index: Matched Set") + 
  ylab("Density of \nthe Poor") + 
  xlim(min(dat$wealth), max(dat$wealth)) +
  theme_bw() +
  theme(
    legend.position="none", 
    axis.title.y = element_text(size = 10),
    axis.title.x = element_text(size = 10)) + 
  scale_y_discrete(breaks=c(0, 1), labels=c("Low", "High"))

### Raw Set
density.wealth.r= ggplot() + geom_point(
  aes(
    y=as.factor(dat$large), 
    x=dat$wealth, 
    colour=dat$large,
    alpha = 1/length(dat$large)), 
  position = position_jitter(width = 5)) +
  xlab("Wealth Index: Raw Set") + 
  ylab("Density of \nthe Poor") + 
  xlim(min(dat$wealth), max(dat$wealth)) +
  theme_bw() +
  theme(
    legend.position="none", 
    axis.title.y = element_text(size = 10),
    axis.title.x = element_text(size = 10)) + 
  scale_y_discrete(breaks=c(0, 1), labels=c("Low", "High"))

library(cowplot) # install.packages("cowplot")
plot_grid(density.wealth.m,density.wealth.r,  nrow = 2)
```


```{r , echo=FALSE, message=FALSE, warning=FALSE}
# balance:distance:plot
# Density Plot: Propensity Scores, by Treatment Condition and By DIscarded 
Distance = m.out$distance
Sample = recode(as.numeric(as.vector(m.out$discarded)), "0 = 'Matched' ; 1 = 'Raw' ")
Density = recode(as.numeric(as.vector(m.out$treat)), "0 = 'Low' ; 1 = 'High' ")



library(ggplot2)
#distance.p=
ggplot() + geom_density(aes(x=Distance, colour=Sample, linetype=Density), alpha=.1) +
  ylab("Estimated Density") + 
  xlab("Distance") + 
  theme_bw() +
  theme(
    axis.title.y = element_text(size = 10), 
    axis.title.x = element_text(size = 10),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 10)) + 
  scale_y_discrete(breaks=c(0, 1), labels=c("Low", "High"))
```